//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<System.DateTime> Fecha_De_Nacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Procedencia { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<int> idCiudad { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
